# CMake generated Testfile for 
# Source directory: D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests
# Build directory: D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-tiny "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-tiny.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny PROPERTIES  LABELS "tiny;gh" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;16;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-tiny "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-tiny.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny PROPERTIES  LABELS "tiny;gh" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;16;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-tiny "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-tiny.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny PROPERTIES  LABELS "tiny;gh" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;16;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-tiny "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-tiny.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny PROPERTIES  LABELS "tiny;gh" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;16;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-tiny NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-tiny.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-tiny.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny.en PROPERTIES  LABELS "tiny;en;gh" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;23;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-tiny.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-tiny.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny.en PROPERTIES  LABELS "tiny;en;gh" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;23;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-tiny.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-tiny.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny.en PROPERTIES  LABELS "tiny;en;gh" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;23;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-tiny.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-tiny.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-tiny.en PROPERTIES  LABELS "tiny;en;gh" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;23;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-tiny.en NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-base "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-base.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;30;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-base "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-base.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;30;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-base "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-base.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;30;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-base "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-base.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base PROPERTIES  LABELS "base" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;30;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-base NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-base.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-base.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base.en PROPERTIES  LABELS "base;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;37;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-base.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-base.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base.en PROPERTIES  LABELS "base;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;37;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-base.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-base.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base.en PROPERTIES  LABELS "base;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;37;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-base.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-base.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-base.en PROPERTIES  LABELS "base;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;37;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-base.en NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-small "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-small.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small PROPERTIES  LABELS "small" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;44;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-small "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-small.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small PROPERTIES  LABELS "small" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;44;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-small "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-small.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small PROPERTIES  LABELS "small" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;44;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-small "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-small.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small PROPERTIES  LABELS "small" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;44;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-small NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-small.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-small.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small.en PROPERTIES  LABELS "small;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;51;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-small.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-small.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small.en PROPERTIES  LABELS "small;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;51;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-small.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-small.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small.en PROPERTIES  LABELS "small;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;51;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-small.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-small.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-small.en PROPERTIES  LABELS "small;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;51;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-small.en NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-medium "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-medium.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium PROPERTIES  LABELS "medium" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;58;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-medium "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-medium.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium PROPERTIES  LABELS "medium" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;58;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-medium "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-medium.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium PROPERTIES  LABELS "medium" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;58;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-medium "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-medium.bin" "-l" "fr" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium PROPERTIES  LABELS "medium" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;58;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-medium NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-medium.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-medium.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium.en PROPERTIES  LABELS "medium;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;65;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-medium.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-medium.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium.en PROPERTIES  LABELS "medium;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;65;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-medium.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-medium.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium.en PROPERTIES  LABELS "medium;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;65;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-medium.en "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-medium.en.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-medium.en PROPERTIES  LABELS "medium;en" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;65;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-medium.en NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-whisper-cli-large "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Debug/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-large.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-large PROPERTIES  LABELS "large" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;72;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-whisper-cli-large "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/Release/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-large.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-large PROPERTIES  LABELS "large" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;72;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-whisper-cli-large "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/MinSizeRel/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-large.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-large PROPERTIES  LABELS "large" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;72;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-whisper-cli-large "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/bin/RelWithDebInfo/whisper-cli.exe" "-m" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/models/for-tests-ggml-large.bin" "-f" "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/samples/jfk.wav")
  set_tests_properties(test-whisper-cli-large PROPERTIES  LABELS "large" _BACKTRACE_TRIPLES "D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;72;add_test;D:/Angsss/ai-accounting-assistant/src/whisper/whisper.cpp/tests/CMakeLists.txt;0;")
else()
  add_test(test-whisper-cli-large NOT_AVAILABLE)
endif()
